// Auto-generated by scripts/generate-demo-authors.mjs — do not edit by hand.
// 每个 demo 组件文件的创建者 GitHub login，slug 与 Demo.tsx 中的 DemoSlug 对应。
export const DEMO_AUTHORS: Record<string, string> = {
  'agent-channel-new-user': 'sheer-creator',
  'automation-popover': 'sheer-creator',
};
